app/AppLoader.scala

Disclaimer: I can't guarantee this this is actually a bonobo, but it looks like one to me.
```
.-""--.
_/-=-.   \
(_|a a/   |_
/ "  \   ,_)
_    \`=' /__/
/ \_  .;--'  `-.
\___)//      ,  \
\ \/;        \  \
\_.|         | |
.-\ '     _/_/
.'  _;.    (_  \
/  .'   `\   \\_/
|_ /       |  |\\
/  _)       /  / ||
jgs /  /       _/  /  //
\_/       ( `-/  ||
/  /   \\ .-.
\_/     \'-'/
Welcome to Bonobo          `"`
2015-11-03 10:35:21,963 [application-akka.actor.default-dispatcher-5] INFO  a.e.s.Slf4jLogger - Slf4jLogger started
2015-11-03 10:35:21,965 [ForkJoinPool-1-worker-0] INFO  play.api.Play - Application started (Dev)
```

Add ascii monkey at startup

---

app/store/Dynamo.scala

We were scanning DynamoDb for equality `email = :some_value`, but in the case of a name (for example) we might want to search only by the last name. Using the`contains(email, :some_value)` returns more relevant results in most of the cases.

Improve search, remove duplicates and sort results

---

app/views/openCreateKey.scala.html

Update open registration form to render fields on 2 columns.

Redesign open registration form

---

app/components/AppComponents.scala
app/controllers/Application.scala
app/controllers/CommercialForm.scala
app/controllers/DeveloperForm.scala
app/email/AwsEmailClient.scala
app/logic/ApplicationLogic.scala
app/logic/CommercialFormLogic.scala
app/util/AWSConstants.scala
app/views/editUser.scala.html
app/views/main.scala.html
app/views/renderMessage.scala.html
app/views/showKeys.scala.html
build.sbt
cloudformation.json
conf/routes
integration-test/scala/integration/IntegrationSpecBase.scala
integration-test/scala/integration/IntegrationTests.scala
test/controllers/ApplicationSpec.scala

- Create email client
- Send emails when:
- a commercial request has been sent
- a new key has been created

Send emails

---

app/controllers/Application.scala
app/controllers/CommercialForm.scala
app/controllers/Forms.scala
app/email/AwsEmailClient.scala
app/logic/ApplicationLogic.scala
app/logic/DeveloperFormLogic.scala
app/models/models.scala
app/store/Dynamo.scala
app/views/createKey.scala.html
app/views/createUser.scala.html
app/views/editKey.scala.html
app/views/editUser.scala.html
app/views/showKeys.scala.html
integration-test/scala/integration/IntegrationSpecBase.scala
integration-test/scala/integration/IntegrationTests.scala
test/controllers/ApplicationSpec.scala

The `productName` and `productUrl` fields have been moved to the `KongKey` class.

Change model

---

app/controllers/Migration.scala
conf/application.conf

Fields `name`, `productName` and `productUrl` are marked as `unspecified` if empty.

Handle empty fields

---

mashery-migration-script/download-from-mashery.sh
mashery-migration-script/send-to-bonobo.rb

Running this against CODE now and it seems to work :pray:

Mashery migration scripts

---

app/controllers/Migration.scala
app/logic/ApplicationLogic.scala
app/logic/CommercialFormLogic.scala
app/logic/DeveloperFormLogic.scala
app/store/Dynamo.scala
cloudformation.json
integration-test/resources/mashery.json
integration-test/scala/integration/IntegrationTests.scala
integration-test/scala/integration/fixtures/BonoboKeysTableFixture.scala
integration-test/scala/integration/fixtures/BonoboUserTableFixture.scala
integration-test/scala/integration/fixtures/KongFixture.scala
test/controllers/ApplicationSpec.scala

and a method that uses that index to check if a given email address is already registered.
Doing this with a scan instead of an index query is unusably slow.

Add index on the users table email field in Dynamo

---

app/controllers/Application.scala
app/controllers/Forms.scala
app/views/createKey.scala.html
app/views/createUser.scala.html
integration-test/scala/integration/IntegrationTests.scala

Add a `Send email` checkbox for the create user and create key forms.

Add send email checkbox

---

app/email/AwsEmailClient.scala
app/views/editUser.scala.html
app/views/showKeys.scala.html

Instead of using the `Edit user`/`Edit key` links, the entire row is now clickable.

Make row clickable and remove edit link

---

app/controllers/Application.scala
app/controllers/Auth.scala
app/logic/ApplicationLogic.scala
app/logic/DeveloperFormLogic.scala
app/store/Dynamo.scala
app/views/main.scala.html
app/views/renderKeysTable.scala.html
app/views/showKeys.scala.html
conf/routes
public/javascripts/createUser.js
public/javascripts/showKeys.js
test/controllers/ApplicationSpec.scala

- Filter keys page by user's labels
- Change pagination to use AJAX

Filter by labels

---

app/controllers/Auth.scala
build.sbt

And remove temporary workaround
Google group and 2FA check to come in a later PR

Bump play-googleauth

---

public/javascripts/showKeys.js

The show keys table was not showing in Safari.

Fix safari

---

cloudformation.json.CODE
cloudformation.json.PROD

Also separate the CloudFormation templates for CODE and PROD

Enable HTTPS on the ELB

---

app/auth/Authorisation.scala

Only authorise users who are members of the appropriate Google group to access the admin pages

Add a check for admin group membership

---

app/components/AppComponents.scala
app/components/CacheFilter.scala

* Disable caching:
```
Expires: Tue, 03 Jul 2001 06:00:00 GMT
Last-Modified: {now} GMT
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
```
* HSTS:
```
Strict-Transport-Security: max-age=31536000
```
* CSP (Content security policy)
* XSS:
```
X-XSS-Protection: 1; mode=block
```

Set security and cache headers

---

conf/application.conf

See playframework/playframework#5829

Make the request.secure flag work like it used to

---

project/plugins.sbt

Update to Play 2.4.8

---

app/controllers/Application.scala
app/store/Dynamo.scala
conf/application.conf
conf/routes
test/controllers/ApplicationSpec.scala

Creates endpoint to get all registered emails: `/email/$tier/$status`
E.g.
https://bonobo-code.capi.gutools.co.uk/email/developer/active
https://bonobo-code.capi.gutools.co.uk/email/internal/inactive

Add endpoint to get all user emails

---

riff-raff.yaml

Use xenial

---

cloudformation-CODE.yaml
cloudformation-PROD.yaml

after I changed the bucket permissions

Fix s3 download

---

app/email/AwsEmailClient.scala

Not sure why the `.com` does not work, but not a big deal

Update email address

---

cloudformation-CODE.yaml
cloudformation-PROD.yaml

Upgrade instances to t3.micro

---

app/components/AppComponents.scala

Use DKIM validated domain

---

app/components/AppComponents.scala
app/views/commercialRequestKey.scala.html
app/views/createKey.scala.html
app/views/createUser.scala.html
app/views/developerCreateKey.scala.html
app/views/editKey.scala.html
app/views/editUser.scala.html
bonobo.service
build.sbt
cloudformation-CODE.yaml
cloudformation-PROD.yaml
project/plugins.sbt
test/controllers/ApplicationSpec.scala

This restores the previous build. I don't know why I couldn't see the generated ZIP in the s3 bucket, it is now there and I've tested on CODE.

Cleanup build, restore ZIP archive

---

app/store/Dynamo.scala
dev/developer-api-keys/src/main/scala/com/gu/bonobo/Main.scala

Ensures that getting a key by its value is efficient. Functionality trialled in #147.

Use keyValue-index-all-attributes

---

README.md
app/views/createKey.scala.html
app/views/createUser.scala.html
app/views/developerTierWarning.scala.html

Adds a warning about Developer tier keys.

warning on Developer tier keys

---

README.md
scripts/configure-docker.sh
scripts/docker-compose.yml

Updates the local Kong setup to match the versions currently in live (0.14 Kong / 9.5 PostgreSQL).
Updates the Dockers usages to match the how Docker currently works on a 2021 dev laptop (ie. we don't need virtualbox).
Verified locally;  Kong pitches up on http://localhost:8000 and 8001.

Local Kong setup refresh

---

app/store/Dynamo.scala
integration-test/scala/integration/IntegrationTests.scala
integration-test/scala/integration/fixtures/BonoboKeysTableFixture.scala
integration-test/scala/integration/fixtures/KongFixture.scala

Restores the local integration tests (sbt it:test).
Levels the containers we test against up to the same versions as live.
Migrates the container setup and teardown to docker-compose so that it works the same is local dev.
```
sbt it:test
```

Update integration tests

---

app/kong/Kong.scala
app/logic/ApplicationLogic.scala
integration-test/scala/integration/IntegrationSpecBase.scala
integration-test/scala/integration/fixtures/KongFixture.scala
scripts/configure-docker.sh
scripts/migration-apis-to-services/code/add-code-key-auth.json
scripts/migration-apis-to-services/code/add-code-route.json
scripts/migration-apis-to-services/code/add-code-service.json
scripts/migration-apis-to-services/code/go.bash
scripts/migration-apis-to-services/code/migrate-plugins.py
scripts/migration-apis-to-services/prod/add-prod-key-auth.json
scripts/migration-apis-to-services/prod/add-prod-route.json
scripts/migration-apis-to-services/prod/add-prod-service.json
scripts/migration-apis-to-services/prod/go.bash
scripts/migration-apis-to-services/prod/migrate-plugins.py

Migrate CAPI Kong from deprecated API concept to sevices and routes.
Migrate existing keys and rate limits.
Kong 0.13 deprecated the API concept splitting it into Services with Routes.
https://github.com/Kong/kong/blob/master/CHANGELOG.md#0130---20180322
To ever progress into the 1.0 series and beyond we need to migrate our deprecated /apis/internal to a service and route.
Kong specfically askes us todo this ourselves:
https://github.com/Kong/kong/blob/master/UPGRADE.md#upgrade-from-0x-to-10x
This PR does this by:
1) Creating a new Service to represent back end CAPI.
2) Setting up the keyauth plugin on the new service (/service/internal)
3) Iterating through the rate limit plugin configurations attached to /api/internal and copying them to /service/internal
4) Creating a new route to send …

Migrate local Kong from deprecated /apis to /services and /routes.

---

app/kong/Kong.scala
integration-test/scala/integration/IntegrationSpecBase.scala
integration-test/scala/integration/fixtures/KongFixture.scala
scripts/configure-docker.sh

Use plugins and routes helper paths under named service to simplify setup.

Post migration cleanup; don't setup deprecated /apis locally.
