guardian/bonobo

- app/controllers/OpenForm.scala
- app/logic/OpenFormLogic.scala
- app/store/Dynamo.scala
- conf/routes
I modified `createUser` to return a key instead of a userId. This has the following advantages:
* code is shorter and saves a db query
* `dynamo.getKeyWithUserId` becomes useless (we already had `getKeysWithUserId` btw)
* the URL after a user has been created through OpenForm is now `?key=<key>` instead of `?userId=<userId>`, which is slightly better since we don't disclose internal information.
> OpenForm refactor and cleanup

- app/controllers/Application.scala
- app/controllers/CommercialForm.scala
- app/controllers/DeveloperForm.scala
- app/controllers/Forms.scala
- app/email/AwsEmailClient.scala
- app/models/models.scala
- app/store/Dynamo.scala
- app/views/commercialRequestKey.scala.html
- integration-test/scala/integration/IntegrationTests.scala
- test/controllers/ApplicationSpec.scala
- Add the `contentFormat` field for the commercial form
- Make all form fields required (except for `key`)
> Add field contentFormat and make fields required

- app/components/AppComponents.scala
- app/controllers/Application.scala
- app/controllers/Migration.scala
- app/kong/Kong.scala
- app/logic/CommercialFormLogic.scala
- app/logic/DeveloperFormLogic.scala
- app/models/models.scala
- app/store/Dynamo.scala
- app/views/createUser.scala.html
- app/views/editKey.scala.html
- build.sbt
- conf/routes
- integration-test/resources/mashery.json
- integration-test/scala/integration/IntegrationSpecBase.scala
- integration-test/scala/integration/IntegrationTests.scala
- integration-test/scala/integration/MigrationIntegrationTests.scala
- test/controllers/ApplicationSpec.scala
- Migration endpoint has been added in `controllers/Migration.scala`. The endpoint accepts a POST with a json body containing a list of users and saves a new consumer with his keys to Kong and DynamoDb. If the key is marked as `Inactive` it will be deleted from Kong.
- Use enumeratum for Tier model.
- Tests and a json example file have been added.
- Returns a Json containing:
- the number of successfully added users
- the number of successfully added keys
- the list of users with conflicts
- the list of keys with conflicts
> Migrate endpoint

- app/models/models.scala
This fixes the bug from the migration endpoint. The Kong `createdAt` was being used instead of the Mashery create date.
> Use mashery date to create the kong key

- app/controllers/Migration.scala
- app/models/models.scala
Kong occasionally generates duplicate UUIDs (!!) for consumer IDs. Work
around by only trying to create one key at a time.
Also better error handling and logging.
> Don't migrate things in parallel because Kong doesn't like it

- app/store/Dynamo.scala
Due to the model change, the `productName` field now belongs to the keys table.
> Fix search by product name

- app/views/commercialRequestKey.scala.html
- app/views/createKey.scala.html
- app/views/createUser.scala.html
- app/views/developerCreateKey.scala.html
- app/views/editKey.scala.html
- app/views/editUser.scala.html
- app/views/mainOpenForm.scala.html
The form's labels have been updated not to show `*` anymore, since in a previous PR all the fields (except for `key`) have been made required.
> Minor views fixes

- app/views/main.scala.html
Previously when you click the search button nothing happened, because the type was not `submit` CC @LATaylor-guardian
> search button should be type submit

- data-pipeline.json
I've set up AWS Data Pipeline to backup the keys and users tables to S3 every day.
> Add a Data Pipeline to backup the Dynamo tables to S3

- app/email/AwsEmailClient.scala
When we decide not to send an email (because we are in a pre-prod environment), we were not completing the promise, so the future never completed.
> Fix hanging promise when using dummy email sending logic

- app/controllers/Auth.scala
Not sure why [google-auth](https://github.com/guardian/play-googleauth) is not checking the domain, as I would have expecting it do the check, but [flexible code check the actual email address domain of the user](https://github.com/guardian/flexible-content/blob/d04957c030a00fb513046ff5f50a8b5e5f413c96/flexible-content-composer-backend/src/main/scala/com/gu/flexiblecontent/composerbackend/dispatcher/PanDomainAuthenticatedUser.scala#L215-L225) so do the same.
@cb372 @adamnfish @sihil
> [Security] Check that the user is guardian staff

- app/controllers/Application.scala
- cloudformation.json.CODE
- cloudformation.json.PROD
- conf/logback.xml
1. Enable ELB access logs with CloudFormation
2. Add access logs to the Bonobo app, to provide better details about the user in a separate `audit.log` file.
The format of the new Bonobo log file is e.g.:
```
2016-02-16 17:39:20,056 - tom.forbes@guardian.co.uk GET /
2016-02-16 17:39:25,780 - tom.forbes@guardian.co.uk GET /key/search?query=test
2016-02-16 17:39:28,819 - tom.forbes@guardian.co.uk GET /user/<id>/edit
2016-02-16 17:39:31,852 - tom.forbes@guardian.co.uk POST /user/<id>/edit - Some(Map(csrfToken -> ArrayBuffer(<token>), name -> ArrayBuffer(Chris Test), email -> ArrayBuffer(chris.birchall+testtest@theguardian.com), companyName -> ArrayBuffer(The Guardian - testing), companyUrl -> ArrayBuffer(http://theguardian.com), labelIds -> ArrayBuffer()))
```
> Improve Bonobo access logging

- app/components/AppComponents.scala
- app/components/HttpsRedirectFilter.scala
- conf/application.conf
This is one of the things that came out of our security review.
Both CODE + PROD still listen on port 80.
A filter in the play app redirects all http requests to https by default. This can be disabled with the httpsRedirectFilter.enabled config item, for running locally.
> Redirect http -> https on Bonobo

- conf/application.conf
First curl is made using `secure` set to true.
> Make the Play session cookie secure

- app/email/AwsEmailClient.scala
This is dirty workaround but as `request.secure` is broken.
> Use https url in the email

- conf/application.conf
If we set it to true then the session becomes a secure cookie, which doesn't work because Play runs on http://localhost:9000
I've updated the CODE and PROD config files to overwrite it to true.
> Set session.secure=false when running locally

- app/models/models.scala
- app/store/Dynamo.scala
- integration-test/scala/integration/IntegrationTests.scala
- test/controllers/ApplicationSpec.scala
- Now that the kong migration is complete, the kongId attribute has been removed
from the keys table in Dynamo for all keys (the canonical source for the consumer id provided by Kong is now kongConsumerId). This means the kongId field can be removed from the KongKey model within Bonobo.
> Bonobo - remove kongId from KongKey model.

- scripts/configure-docker.sh
- scripts/docker-compose.yml
addresses #112 by internally changing the `scripts/configure-docker.sh` script to use `docker-compose` and `docker-compose.yml`. It's not the cleanest solution (I think when the new `HEALTHCHECK` directive has better support this can be made much cleaner) but it works locally - which I believe is the purpose here.
I don't know how to test it further than those two POST requests returning 201's.
I often see a warning appear, the consequences of which I'm unfamiliar with:
> kong_1       | [WARN] Cannot auto-join the cluster because no nodes were found
although the whole thing still seems to work.
You may also be interested in more advanced setups by the kong guys themselves [here](https://github.com/Mashape/docker-kong/blob/master/compose/docker-compose.yml)
If there needs to be some sort …
> docker-compose-ify dev bootstrap scripts

- app/components/AppComponents.scala
- conf/application.conf
For use during Kong upgrades. This will reject all requests (besides /healthcheck) with:
`503 - Server is down for maintenance, please try again later`
This is controlled with a config item, `maintenanceMode`, and Bonobo has to be redeployed to switch on/off. This feature will be used so rarely that it's not really worth doing something more sophisticated.
> Maintenance mode

- app/controllers/csrf/CSRFSupport.scala
- project/plugins.sbt
The [migration to play 2.6](https://github.com/guardian/bonobo/pull/131) break the CSRF token to be populated correcly
@tackley
> Fix broken registration

- app/logic/DeveloperFormLogic.scala
For some reasons, sometimes Kong will return a 404 when trying to delete a consumer, even if that user has an active key in the bonobo database. I'm catching these errors and cleaning up the DB anyway.
> Delete keys in Dynamo even if Kong fails

- app/kong/Kong.scala
Brings bonobo in line with [this change](https://github.com/guardian/content-api/pull/2184) to the kong rate-limiting plugin.
Drastically reduces DB connections (and instance size), at the cost of less reliable rate-limiting
> Use 'local' rate-limiting policy

- bonobo.service
- cloudformation-CODE.yaml
- cloudformation-PROD.yaml
The bonobo build failed. That's because I configured the `content-api-dist` repo to remove files older than 1 year. It turns out the build is generating a tar but the launch config is looking for a zip.
Have already tested on CODE
> Update build with correct artefact

- app/store/Dynamo.scala
- build.sbt
- dev/developer-api-keys/README.md
- dev/developer-api-keys/src/main/scala/com/gu/bonobo/Main.scala
See newly added README for context.
Regarding the new index `keyValue-index-all-attributes` that was created. This was due to the method `getKeyWithValue()` performing a full table scan. In a subsequent PR, I will update the application to use this new index. Note I haven't cloud formed the new index since the resources associated with the Bonobo cloudformation template(s) have drifted; I see resolving this as a separate task.
> Script to look at developer tier keys

- app/kong/Kong.scala
- build.sbt
- conf/application.conf
- scripts/backfill-created-dates.py
- test/kong/KongSpec.scala
Fixes incorrect 1970 creation dates for newly created keys.
Kong API 0.14 and high renders date times as epoch seconds. Older versions of the Kong API seem to have used milliseconds.
An old version of Kong (0.9) returning milliseconds. 
We once used Kong 0.5 and bonobo was probably coded against that.
> Key creation dates fix

- riff-raff.yaml
Deploy with `ubuntu-bionic-capi` base image which has the same java8 and and logstash roles as the old xenial image.
Bonoho code still works.
Logstash still stashing
instance logstash logs not showing errors.
> Deploy bonobo with a bionic Java 8 base image

- app/views/renderKeysTable.scala.html
This reverts commit 9200b1716b0befb322c58fd854a005fe4a42c33c (pushed directly to master by mistake) and reintroduces the changes to follow best practice.
A new field has been added to the All Keys view page in bonobo to display the key's extendedAt field if it exists.
Run bonobo locally and point the application.conf file to the PROD dynamoDB tables (the extendedAt field does not exist in CODE).
Check All Keys view page for the extendedAt field or search for a specific user that you know has an extendedAt date and look for the date being displayed in correct format.
(You can also just look at Bonobo PROD as the change is already reflected there)
Field should display correct date in correct format if it exists and should handle null values gracefully by displaying nothing.
This is a …
> Rollback and reintroduce extended at field
